# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pkg.proto import fnsdb_pb2 as pkg_dot_proto_dot_fnsdb__pb2


class ShoppingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/grpc.ShoppingService/Add',
                request_serializer=pkg_dot_proto_dot_fnsdb__pb2.AddRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_fnsdb__pb2.AddResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/grpc.ShoppingService/List',
                request_serializer=pkg_dot_proto_dot_fnsdb__pb2.ListRequest.SerializeToString,
                response_deserializer=pkg_dot_proto_dot_fnsdb__pb2.ListResponse.FromString,
                )


class ShoppingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoppingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=pkg_dot_proto_dot_fnsdb__pb2.AddRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_fnsdb__pb2.AddResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=pkg_dot_proto_dot_fnsdb__pb2.ListRequest.FromString,
                    response_serializer=pkg_dot_proto_dot_fnsdb__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ShoppingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShoppingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ShoppingService/Add',
            pkg_dot_proto_dot_fnsdb__pb2.AddRequest.SerializeToString,
            pkg_dot_proto_dot_fnsdb__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ShoppingService/List',
            pkg_dot_proto_dot_fnsdb__pb2.ListRequest.SerializeToString,
            pkg_dot_proto_dot_fnsdb__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
