# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/proto/fnsdb.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pkg/proto/fnsdb.proto\x12\x04grpc\",\n\nAddRequest\x12\r\n\x05tg_id\x18\x01 \x01(\x05\x12\x0f\n\x07qr_info\x18\x02 \x01(\t\"\x1c\n\x0b\x41\x64\x64Response\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"B\n\x0bListRequest\x12\r\n\x05tg_id\x18\x01 \x01(\x05\x12\x12\n\nbegin_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\"1\n\x0cListResponse\x12!\n\tpurchases\x18\x01 \x03(\x0b\x32\x0e.grpc.Purchase\"\x89\x01\n\x08Purchase\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06market\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x10\n\x08quantity\x18\x07 \x01(\x05\x12\x0f\n\x07\x62\x61rcode\x18\x08 \x01(\t2l\n\x0fShoppingService\x12*\n\x03\x41\x64\x64\x12\x10.grpc.AddRequest\x1a\x11.grpc.AddResponse\x12-\n\x04List\x12\x11.grpc.ListRequest\x1a\x12.grpc.ListResponseB!Z\x1f./shopping-expenses.v1;shoppingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.fnsdb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037./shopping-expenses.v1;shopping'
  _globals['_ADDREQUEST']._serialized_start=31
  _globals['_ADDREQUEST']._serialized_end=75
  _globals['_ADDRESPONSE']._serialized_start=77
  _globals['_ADDRESPONSE']._serialized_end=105
  _globals['_LISTREQUEST']._serialized_start=107
  _globals['_LISTREQUEST']._serialized_end=173
  _globals['_LISTRESPONSE']._serialized_start=175
  _globals['_LISTRESPONSE']._serialized_end=224
  _globals['_PURCHASE']._serialized_start=227
  _globals['_PURCHASE']._serialized_end=364
  _globals['_SHOPPINGSERVICE']._serialized_start=366
  _globals['_SHOPPINGSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
